apiVersion: v1
kind: Service
metadata:
  name: phpapp
  labels:
    app: phpapp
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: phpapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpapp
  template:
    metadata:
      labels:
        app: phpapp
    spec:
      containers:
      - name: phpapp
        image: docker.io/ytooyama/php-demo:v1.0
        ports:
        - containerPort: 80