# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: '2.1'
orbs:
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  create-update:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout 
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - kubernetes/install-kubectl
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yaml
          resource-name: deployment/phpapp
          show-kubectl-command: true
workflows: null
